
services:
  web:
    build: .
    container_name: my_fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/movies
      - ./movies.db:/movies.db
      - ./alembic:/movies/alembic
    depends_on:
      - redis
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///movies.db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
    command: celery -A app.tasks.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/movies

  flower:
    image: mher/flower
    container_name: flower
    depends_on:
      - redis
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
#    command: celery -A app.tasks.celery flower
#    command: flower --broker=redis://redis:6379/0

  migrations:
    build: .
    container_name: alembic_migrations
    command: alembic upgrade head
    depends_on:
      - web
    volumes:
      - .:/movies
      - ./alembic:/movies/alembic
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///movies.db










