
services:
  db:
    image: nouchka/sqlite3:latest
    container_name: sqlite_database
    volumes:
      - ./app:/app
    environment:
      - SQLITE_DATABASE_PATH=/app/movies.db

  redis:
    image: redis:7.2.7
    container_name: redis_cache
    ports: - "6379:6379"

  movies:
    container_name: movies_app
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
      - redis





