version: '2.32.4-desktop.1'
services:
  db:
    image: nouchka/sqlite3:latest
    container_name: sqlite_database
    volumes:
      - ./app:/app
    environment:
      - SQLITE_DATABASE_PATH=/app/movies.db

